include:
    - docker-compose.yml

services:
    # 应用部署相关
    next-monitor-server:
        image: bitnami/node:20.15.1
        container_name: next-monitor-server
        ports:
            - 8081:8081
        volumes:
            - ../:/app/monitor
        # command: "node /app/server.js"
        environment:
            - NODE_ENV=production
        working_dir: /app/monitor/apps/backend/monitor
        command: 'node dist/main.js'
        depends_on:
            - next-monitor-postgresql
            - next-monitor-redis
            - next-monitor-clickhouse
            # - next-monitor-kafka
    # next-monitor-caddy:
    #     image: caddy:latest
    #     container_name: next-monitor-caddy
    #     ports:
    #         - 80:80
    #         - 443:443
    #         - 443:443/udp
    #         - 5173:5173
    #     volumes:
    #         - ./caddy:/etc/caddy
    #         # - ../:/app
    #         - ../apps/frontend/monitor/dist:/app/frontend/monitor/dist
    #     # command: ["caddy", "run", "--resume", "--config", "/etc/caddy/Caddyfile"]
