# 这是只能外部访问的配置
version: '3'

services:
    # next-monitor-kafka:
    #     image: bitnami/kafka:3.9.0
    #     container_name: next-monitor-kafka
    #     ports:
    #         # - '9092:9092'
    #         - '9093:9093'
    #         - '9094:9094'
    #     environment:
    #         - KAFKA_CFG_NODE_ID=1
    #         - KAFKA_CFG_PROCESS_ROLES=broker,controller
    #         - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@192.168.31.16:9093
    #         # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://192.168.31.16:9094
    #         - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
    #         # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://next-monitor-kafka:9092,EXTERNAL://192.168.31.16:9094
    #         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://next-monitor-kafka:9092,EXTERNAL://localhost:9094
    #         # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #         - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    #         - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     # volumes:
    #     #     - ./kafka_data:/bitnami/kafka/data

    next-monitor-clickhouse:
        image: bitnami/clickhouse:25.3.1
        container_name: next-monitor-clickhouse
        ports:
            - 8123:8123
            - 9000:9000
        environment:
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=lauclickhouse
            - CLICKHOUSE_DATABASE=default
    next-monitor-postgresql:
        image: bitnami/postgresql:17.5.0
        container_name: next-monitor-postgresql
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USERNAME=postgres
            - ALLOW_EMPTY_PASSWORD=yes
            - POSTGRESQL_DATABASE=postgres
        volumes:
            - ./postgresql_data:/bitnami/postgresql
    next-monitor-redis:
        image: bitnami/redis:7.4.2
        container_name: next-monitor-redis
        ports:
            - '6379:6379'
        environment:
            - REDIS_PASSWORD=lauredis
networks:
    default:
        name: next-monitor-network
        driver: bridge
